import os
import re
from datetime import date
from html import escape
from typing import Dict, List, Any
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak, KeepTogether
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.pdfgen import canvas
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.cidfonts import UnicodeCIDFont
from utils.market_profile import localize_amount


def _safe(value: Any) -> str:
    return escape(str(value or ""))


def _clean_markdown(value: Any) -> str:
    text = str(value or "")
    text = re.sub(r"```.*?```", "", text, flags=re.S)
    text = re.sub(r"!\[([^\]]*)\]\([^)]+\)", r"\1", text)
    text = re.sub(r"\[([^\]]+)\]\(([^)]+)\)", r"\1 (\2)", text)
    text = re.sub(r"^\s{0,3}#{1,6}\s*", "", text, flags=re.M)
    text = re.sub(r"(\*\*|__)(.*?)\1", r"\2", text)
    text = re.sub(r"`([^`]*)`", r"\1", text)
    text = re.sub(r"^\s*[-*+]\s+", "• ", text, flags=re.M)
    text = re.sub(r"^\s*\d+\.\s+", "• ", text, flags=re.M)
    text = text.replace("---", "")
    text = text.replace("###", "").replace("##", "").replace("#", "")
    text = text.replace("**", "")
    return re.sub(r"\n{3,}", "\n\n", text).strip()


def _safe_md(value: Any) -> str:
    return escape(_clean_markdown(value))


def _append_clean_blocks(story: List[Any], text: Any, body_style, h2_style) -> None:
    cleaned = _clean_markdown(text)
    for block in re.split(r"\n\s*\n", cleaned):
        block = block.strip()
        if not block:
            continue
        first_line = block.splitlines()[0].strip()
        if len(first_line) <= 70 and len(block.splitlines()) == 1 and not first_line.startswith("• "):
            story.append(Paragraph(_safe(first_line), h2_style))
            continue
        story.append(Paragraph(_safe(block).replace("\n", "<br/>"), body_style))


def _money(value: Any, market_profile: Dict[str, Any]) -> str:
    try:
        return localize_amount(float(value), market_profile)
    except (TypeError, ValueError):
        return "N/A"


def _locale_fonts(market_profile: Dict[str, Any]) -> tuple[str, str]:
    language_code = str(market_profile.get("language_code") or "").lower()
    try:
        if language_code.startswith("ja"):
            pdfmetrics.registerFont(UnicodeCIDFont("HeiseiMin-W3"))
            pdfmetrics.registerFont(UnicodeCIDFont("HeiseiKakuGo-W5"))
            return "HeiseiMin-W3", "HeiseiKakuGo-W5"
        if language_code.startswith("zh"):
            pdfmetrics.registerFont(UnicodeCIDFont("STSong-Light"))
            return "STSong-Light", "STSong-Light"
        if language_code.startswith("ko"):
            pdfmetrics.registerFont(UnicodeCIDFont("HYSMyeongJo-Medium"))
            pdfmetrics.registerFont(UnicodeCIDFont("HYGothic-Medium"))
            return "HYSMyeongJo-Medium", "HYGothic-Medium"
    except Exception:
        pass
    return "Helvetica", "Helvetica-Bold"

class NumberedCanvas(canvas.Canvas):
    """
    Two-pass canvas to add running footers with total page count.
    """
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super().showPage()
        super().save()

    def draw_page_decorations(self, page_count):
        self.saveState()
        self.setFont("Helvetica-Bold", 8)
        self.setFillColor(colors.HexColor("#64748B"))
        
        # Draw header (skip on first page)
        if self._pageNumber > 1:
            self.drawString(54, 750, "B Scout Intelligence Report | Location & Business Plan")
            self.setStrokeColor(colors.HexColor("#E2E8F0"))
            self.setLineWidth(0.5)
            self.line(54, 742, letter[0] - 54, 742)

        # Draw footer
        self.setStrokeColor(colors.HexColor("#E2E8F0"))
        self.setLineWidth(0.5)
        self.line(54, 50, letter[0] - 54, 50)
        
        self.setFont("Helvetica", 8)
        self.drawString(54, 38, "CONFIDENTIAL - Generated by B Scout Multi-Agent Network")
        page_text = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(letter[0] - 54, 38, page_text)
        
        self.restoreState()

def generate_business_plan_pdf(
    file_path: str,
    room_id: str,
    business_type: str,
    city: str,
    zones: List[Dict[str, Any]],
    seasonal_forecast: Dict[str, str],
    plan_details: Dict[str, str],
    events: List[Dict[str, Any]] = None,
    land_research: List[Dict[str, Any]] = None,
    demographics: Dict[str, Any] = None,
    anchor_research: List[Dict[str, Any]] = None,
    brightdata_diagnostics: Dict[str, Any] = None,
    traffic_diagnostics: Dict[str, Any] = None,
    competitor_diagnostics: Dict[str, Any] = None,
    demographics_diagnostics: Dict[str, Any] = None,
    anchor_diagnostics: Dict[str, Any] = None,
    land_diagnostics: Dict[str, Any] = None,
    market_profile: Dict[str, Any] = None
):
    # Ensure directory exists
    os.makedirs(os.path.dirname(file_path), exist_ok=True)
    events = events or []
    land_research = land_research or []
    demographics = demographics or {}
    anchor_research = anchor_research or []
    brightdata_diagnostics = brightdata_diagnostics or {}
    traffic_diagnostics = traffic_diagnostics or {}
    competitor_diagnostics = competitor_diagnostics or {}
    demographics_diagnostics = demographics_diagnostics or {}
    anchor_diagnostics = anchor_diagnostics or {}
    land_diagnostics = land_diagnostics or {}
    market_profile = market_profile or {"currency_code": "USD", "currency_symbol": "$", "locale_code": "en_US"}
    body_font, bold_font = _locale_fonts(market_profile)

    # Setup document
    margin = 54  # 0.75 in
    doc = SimpleDocTemplate(
        file_path,
        pagesize=letter,
        leftMargin=margin,
        rightMargin=margin,
        topMargin=margin + 20,
        bottomMargin=margin + 20
    )

    styles = getSampleStyleSheet()
    
    # Premium B Scout palette
    c_primary = colors.HexColor("#111111")
    c_secondary = colors.HexColor("#FF187F")
    c_accent = colors.HexColor("#E6B84A")
    c_dark = colors.HexColor("#334155")
    c_light = colors.HexColor("#FFF7FB")
    c_panel = colors.HexColor("#F8FAFC")

    # Custom typography styles
    title_style = ParagraphStyle(
        'DocTitle',
        parent=styles['Heading1'],
        fontName=bold_font,
        fontSize=26,
        leading=32,
        textColor=c_primary,
        spaceAfter=15
    )

    subtitle_style = ParagraphStyle(
        'DocSubTitle',
        parent=styles['Normal'],
        fontName=body_font,
        fontSize=12,
        leading=16,
        textColor=colors.HexColor("#64748B"),
        spaceAfter=30
    )

    h1_style = ParagraphStyle(
        'H1',
        parent=styles['Heading2'],
        fontName=bold_font,
        fontSize=18,
        leading=22,
        textColor=c_secondary,
        spaceBefore=15,
        spaceAfter=10,
        keepWithNext=True
    )

    h2_style = ParagraphStyle(
        'H2',
        parent=styles['Heading3'],
        fontName=bold_font,
        fontSize=13,
        leading=17,
        textColor=c_accent,
        spaceBefore=12,
        spaceAfter=6,
        keepWithNext=True
    )

    body_style = ParagraphStyle(
        'Body',
        parent=styles['BodyText'],
        fontName=body_font,
        fontSize=10,
        leading=14,
        textColor=c_dark,
        spaceAfter=8
    )

    table_header_style = ParagraphStyle(
        'TableHeader',
        parent=styles['Normal'],
        fontName=bold_font,
        fontSize=9,
        leading=12,
        textColor=colors.white
    )

    table_body_style = ParagraphStyle(
        'TableBody',
        parent=styles['Normal'],
        fontName=body_font,
        fontSize=8.5,
        leading=11,
        textColor=c_dark
    )

    story = []

    # Title & Header
    story.append(Spacer(1, 20))
    story.append(Paragraph("B SCOUT INTELLIGENCE REPORT", title_style))
    story.append(Paragraph(f"Comprehensive Feasibility Study & Business Plan for a new <b>{_safe_md(business_type)}</b> in <b>{_safe_md(city)}</b>", subtitle_style))
    
    # Session Details
    metadata_data = [
        [Paragraph("<b>Session ID:</b>", table_body_style), Paragraph(room_id, table_body_style)],
        [Paragraph("<b>Analysis Date:</b>", table_body_style), Paragraph(date.today().isoformat(), table_body_style)],
        [Paragraph("<b>Workflow Mode:</b>", table_body_style), Paragraph("Parallel agent research with final synthesis", table_body_style)],
        [Paragraph("<b>Market Locale:</b>", table_body_style), Paragraph(
            f"{_safe(market_profile.get('country_name'))} | {_safe(market_profile.get('language_name'))} | "
            f"{_safe(market_profile.get('currency_code'))} ({_safe(market_profile.get('currency_symbol'))})",
            table_body_style
        )],
    ]
    meta_table = Table(metadata_data, colWidths=[100, letter[0] - 2 * margin - 100])
    meta_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), c_panel),
        ('BOX', (0,0), (-1,-1), 1, colors.HexColor("#E2E8F0")),
        ('INNERGRID', (0,0), (-1,-1), 0.5, colors.HexColor("#F1F5F9")),
        ('TOPPADDING', (0,0), (-1,-1), 6),
        ('BOTTOMPADDING', (0,0), (-1,-1), 6),
        ('LEFTPADDING', (0,0), (-1,-1), 10),
        ('RIGHTPADDING', (0,0), (-1,-1), 10),
    ]))
    story.append(meta_table)
    story.append(Spacer(1, 25))

    recommendation = zones[0] if zones else {}
    population_label = demographics.get("population_label") or (
        f"{int(demographics.get('population')):,}" if demographics.get("population") else "Unavailable"
    )
    anchor_lookup = {item.get("zone_name"): item for item in anchor_research}
    top_anchor = max(
        anchor_research,
        key=lambda item: float(item.get("anchor_score") or 0),
        default={},
    )

    def _anchor_counts_text(item: Dict[str, Any]) -> str:
        counts = item.get("anchor_counts") or {}
        return (
            f"Malls: {counts.get('malls', 0)}; Markets: {counts.get('public_markets', 0)}; "
            f"Colleges/Universities: {counts.get('colleges_universities', 0)}; "
            f"Schools: {counts.get('schools', 0)}; Transit: {counts.get('transit_hubs', 0)}"
        )

    def _anchor_impact_text(item: Dict[str, Any]) -> str:
        counts = item.get("anchor_counts") or {}
        impacts = []
        if counts.get("malls"):
            impacts.append("mall evidence supports shopper and leisure foot traffic")
        if counts.get("public_markets"):
            impacts.append("market evidence supports daily essentials traffic")
        if counts.get("colleges_universities"):
            impacts.append("college evidence supports student and staff demand")
        if counts.get("schools"):
            impacts.append("school evidence supports family and weekday routine demand")
        if counts.get("transit_hubs"):
            impacts.append("transit evidence supports commuter visibility")
        return "; ".join(impacts) if impacts else "No live demand-anchor evidence returned for this zone."

    data_confidence = "Live Bright Data evidence captured" if any([
        traffic_diagnostics.get("status") == "live",
        competitor_diagnostics.get("status") == "live",
        demographics_diagnostics.get("status") == "live",
        anchor_diagnostics.get("status") == "live",
    ]) else "Live Bright Data evidence incomplete - validate before committing capital"
    top_risk = "Competition and foot-traffic evidence require field validation" if data_confidence.startswith("Live Bright Data evidence incomplete") else "Execution risk: lease terms, conversion rate, and operating costs must be validated."
    summary_rows = [
        [Paragraph("<b>Recommended Site</b>", table_body_style), Paragraph(_safe_md(recommendation.get("name", "No validated site")), table_body_style)],
        [Paragraph("<b>Opportunity Score</b>", table_body_style), Paragraph(f"{recommendation.get('opp_score', 0)}/10", table_body_style)],
        [Paragraph("<b>Traffic Evidence</b>", table_body_style), Paragraph(
            f"{_safe_md(recommendation.get('traffic_source', 'unknown'))}; confidence: {_safe_md(recommendation.get('traffic_confidence', 'unknown'))}",
            table_body_style
        )],
        [Paragraph("<b>Competitor Evidence</b>", table_body_style), Paragraph(
            f"{recommendation.get('competitor_count', 0)} Bright Data result(s); confidence: {_safe_md(recommendation.get('competitor_confidence', 'unknown'))}",
            table_body_style
        )],
        [Paragraph("<b>Population Evidence</b>", table_body_style), Paragraph(
            f"{_safe_md(population_label)}; confidence: {_safe_md(demographics.get('confidence', 'unknown'))}",
            table_body_style
        )],
        [Paragraph("<b>Demand Anchors</b>", table_body_style), Paragraph(
            (
                f"{_safe_md(top_anchor.get('zone_name'))}: score {top_anchor.get('anchor_score', 0)}/10; "
                f"{_safe_md(_anchor_counts_text(top_anchor))}"
            ) if top_anchor else "No live nearby-anchor evidence returned",
            table_body_style
        )],
        [Paragraph("<b>Data Confidence</b>", table_body_style), Paragraph(_safe_md(data_confidence), table_body_style)],
        [Paragraph("<b>Top Risk</b>", table_body_style), Paragraph(_safe_md(top_risk), table_body_style)],
    ]
    story.append(Paragraph("1. Findings Summary", h1_style))
    summary_table = Table(summary_rows, colWidths=[125, letter[0] - 2 * margin - 125])
    summary_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), c_light),
        ('BOX', (0,0), (-1,-1), 1, colors.HexColor("#FBCFE8")),
        ('INNERGRID', (0,0), (-1,-1), 0.5, colors.HexColor("#FCE7F3")),
        ('TOPPADDING', (0,0), (-1,-1), 7),
        ('BOTTOMPADDING', (0,0), (-1,-1), 7),
        ('LEFTPADDING', (0,0), (-1,-1), 9),
        ('RIGHTPADDING', (0,0), (-1,-1), 9),
    ]))
    story.append(summary_table)
    story.append(Spacer(1, 16))

    story.append(Paragraph("2. Data Source & Validation Status", h1_style))
    diagnostics_rows = [[
        Paragraph("Evidence Area", table_header_style),
        Paragraph("Status", table_header_style),
        Paragraph("Source", table_header_style),
        Paragraph("Count", table_header_style),
    ]]
    diagnostics_rows.extend([
        [
            Paragraph("Events", table_body_style),
            Paragraph(_safe_md(brightdata_diagnostics.get("status", "unknown")), table_body_style),
            Paragraph(_safe_md(brightdata_diagnostics.get("source", "unknown")), table_body_style),
            Paragraph(str(brightdata_diagnostics.get("events_count", 0)), table_body_style),
        ],
        [
            Paragraph("Traffic", table_body_style),
            Paragraph(_safe_md(traffic_diagnostics.get("status", "unknown")), table_body_style),
            Paragraph(_safe_md(traffic_diagnostics.get("source", "unknown")), table_body_style),
            Paragraph(str(traffic_diagnostics.get("evidence_count", 0)), table_body_style),
        ],
        [
            Paragraph("Demographics", table_body_style),
            Paragraph(_safe_md(demographics_diagnostics.get("status", "unknown")), table_body_style),
            Paragraph(_safe_md(demographics_diagnostics.get("source", "unknown")), table_body_style),
            Paragraph(str(demographics_diagnostics.get("evidence_count", 0)), table_body_style),
        ],
        [
            Paragraph("Demand Anchors", table_body_style),
            Paragraph(_safe_md(anchor_diagnostics.get("status", "unknown")), table_body_style),
            Paragraph(_safe_md(anchor_diagnostics.get("source", "unknown")), table_body_style),
            Paragraph(str(anchor_diagnostics.get("anchor_evidence_count", 0)), table_body_style),
        ],
        [
            Paragraph("Competitors", table_body_style),
            Paragraph(_safe_md(competitor_diagnostics.get("status", "unknown")), table_body_style),
            Paragraph(_safe_md(competitor_diagnostics.get("source", "unknown")), table_body_style),
            Paragraph(str(competitor_diagnostics.get("competitor_evidence_count", 0)), table_body_style),
        ],
        [
            Paragraph("Land Listings", table_body_style),
            Paragraph(_safe_md(land_diagnostics.get("status", "unknown")), table_body_style),
            Paragraph(_safe_md(land_diagnostics.get("source", "unknown")), table_body_style),
            Paragraph(str(land_diagnostics.get("live_listing_count", 0)), table_body_style),
        ],
    ])
    diagnostics_table = Table(diagnostics_rows, colWidths=[110, 135, 185, 74])
    diagnostics_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), c_secondary),
        ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor("#CBD5E1")),
        ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.white, c_panel]),
        ('TOPPADDING', (0,0), (-1,-1), 6),
        ('BOTTOMPADDING', (0,0), (-1,-1), 6),
        ('LEFTPADDING', (0,0), (-1,-1), 7),
        ('RIGHTPADDING', (0,0), (-1,-1), 7),
    ]))
    story.append(diagnostics_table)
    story.append(Spacer(1, 20))

    story.append(Paragraph("3. Population & Demand Anchor Analysis", h1_style))
    story.append(Paragraph(
        "This section summarizes the live Bright Data evidence for total population and nearby demand generators. "
        "Anchor counts are SERP evidence counts, not a complete registry of every mall, market, school, college, or transit hub.",
        body_style
    ))

    population_rows = [
        [Paragraph("<b>Population Figure</b>", table_body_style), Paragraph(_safe_md(population_label), table_body_style)],
        [Paragraph("<b>Student/Youth Demographics</b>", table_body_style), Paragraph(_safe_md(demographics.get("student_population", "Unavailable")), table_body_style)],
        [Paragraph("<b>Source</b>", table_body_style), Paragraph(_safe_md(demographics.get("source", "unknown")), table_body_style)],
        [Paragraph("<b>Confidence</b>", table_body_style), Paragraph(_safe_md(demographics.get("confidence", "unknown")), table_body_style)],
    ]
    population_table = Table(population_rows, colWidths=[125, letter[0] - 2 * margin - 125])
    population_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), c_panel),
        ('BOX', (0,0), (-1,-1), 1, colors.HexColor("#E2E8F0")),
        ('INNERGRID', (0,0), (-1,-1), 0.5, colors.HexColor("#F1F5F9")),
        ('TOPPADDING', (0,0), (-1,-1), 6),
        ('BOTTOMPADDING', (0,0), (-1,-1), 6),
        ('LEFTPADDING', (0,0), (-1,-1), 8),
        ('RIGHTPADDING', (0,0), (-1,-1), 8),
    ]))
    story.append(population_table)
    story.append(Spacer(1, 10))

    demographic_evidence = demographics.get("evidence") or []
    if demographic_evidence:
        demo_rows = [[
            Paragraph("Population Evidence", table_header_style),
            Paragraph("Snippet", table_header_style),
        ]]
        for item in demographic_evidence[:3]:
            demo_rows.append([
                Paragraph(f"<b>{_safe_md(item.get('title'))}</b>", table_body_style),
                Paragraph(_safe_md(item.get("snippet")), table_body_style),
            ])
        demo_table = Table(demo_rows, colWidths=[190, 314])
        demo_table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), c_dark),
            ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor("#CBD5E1")),
            ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.white, c_panel]),
            ('VALIGN', (0,0), (-1,-1), 'TOP'),
            ('TOPPADDING', (0,0), (-1,-1), 6),
            ('BOTTOMPADDING', (0,0), (-1,-1), 6),
            ('LEFTPADDING', (0,0), (-1,-1), 7),
            ('RIGHTPADDING', (0,0), (-1,-1), 7),
        ]))
        story.append(demo_table)
        story.append(Spacer(1, 12))

    if anchor_research:
        anchor_rows = [[
            Paragraph("Zone", table_header_style),
            Paragraph("Anchor Evidence", table_header_style),
            Paragraph("Top Place Evidence", table_header_style),
            Paragraph("Business Impact", table_header_style),
        ]]
        for item in anchor_research:
            top_places = []
            for category, places in (item.get("anchors") or {}).items():
                for place in places[:1]:
                    top_places.append(f"{category.replace('_', ' ')}: {place.get('title')}")
                if len(top_places) >= 5:
                    break
            anchor_rows.append([
                Paragraph(
                    f"<b>{_safe_md(item.get('zone_name'))}</b><br/>Score: {item.get('anchor_score', 0)}/10<br/>"
                    f"Confidence: {_safe_md(item.get('confidence', 'unknown'))}",
                    table_body_style
                ),
                Paragraph(_safe_md(_anchor_counts_text(item)), table_body_style),
                Paragraph(_safe_md("; ".join(top_places) or "No live place titles returned"), table_body_style),
                Paragraph(_safe_md(_anchor_impact_text(item)), table_body_style),
            ])

        anchor_table = Table(anchor_rows, colWidths=[92, 128, 142, 142])
        anchor_table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), c_secondary),
            ('ALIGN', (0,0), (-1,-1), 'LEFT'),
            ('VALIGN', (0,0), (-1,-1), 'TOP'),
            ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor("#CBD5E1")),
            ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.white, c_light]),
            ('TOPPADDING', (0,0), (-1,-1), 6),
            ('BOTTOMPADDING', (0,0), (-1,-1), 6),
            ('LEFTPADDING', (0,0), (-1,-1), 7),
            ('RIGHTPADDING', (0,0), (-1,-1), 7),
        ]))
        story.append(anchor_table)
    else:
        story.append(Paragraph(
            "No live nearby-anchor evidence was returned. Validate malls, markets, colleges, schools, and transit hubs manually before committing capital.",
            body_style
        ))
    story.append(Spacer(1, 20))

    # Section 1: Executive Location Summary
    story.append(Paragraph("4. Geographic & Location Analysis", h1_style))
    story.append(Paragraph(
        "Our location scout and competitor analyst agents mapped commercial zones in detail. "
        "Each zone has been graded based on traffic index, local business saturation, and computed opportunity index:",
        body_style
    ))
    story.append(Spacer(1, 10))

    # Zones Table
    headers = [
        Paragraph("Zone Name", table_header_style), 
        Paragraph("Traffic Evidence", table_header_style),
        Paragraph("Competitor Evidence", table_header_style),
        Paragraph("Saturation Index", table_header_style), 
        Paragraph("Opportunity Score", table_header_style)
    ]
    zone_rows = [headers]
    for z in zones:
        zone_anchor = anchor_lookup.get(z.get("name")) or {}
        anchor_note = (
            f"<br/><font color='#64748B'>Demand anchors: {_safe_md(_anchor_counts_text(zone_anchor))}</font>"
            if zone_anchor
            else ""
        )
        zone_rows.append([
            Paragraph(
                f"<b>{_safe_md(z.get('name'))}</b><br/><font color='#64748B'>{_safe_md(str(z.get('description', ''))[:110])}</font>{anchor_note}",
                table_body_style
            ),
            Paragraph(
                f"{z.get('traffic_score', 0)}/10<br/>{_safe_md(z.get('traffic_source', 'unknown'))}<br/>"
                f"Confidence: {_safe_md(z.get('traffic_confidence', 'unknown'))}",
                table_body_style
            ),
            Paragraph(
                f"{z.get('competitor_count', 0)} result(s)<br/>{_safe_md(z.get('competitor_source', 'unknown'))}<br/>"
                f"Confidence: {_safe_md(z.get('competitor_confidence', 'unknown'))}",
                table_body_style
            ),
            Paragraph(f"{z.get('saturation_score', 0)}/10", table_body_style),
            Paragraph(f"<b>{z.get('opp_score', 0)}/10</b>", table_body_style)
        ])
    
    col_widths = [155, 115, 115, 60, 59]
    zones_table = Table(zone_rows, colWidths=col_widths)
    zones_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), c_secondary),
        ('ALIGN', (0,0), (-1,-1), 'LEFT'),
        ('VALIGN', (0,0), (-1,-1), 'TOP'),
        ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor("#CBD5E1")),
        ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.white, c_light]),
        ('TOPPADDING', (0,0), (-1,-1), 8),
        ('BOTTOMPADDING', (0,0), (-1,-1), 8),
        ('LEFTPADDING', (0,0), (-1,-1), 8),
        ('RIGHTPADDING', (0,0), (-1,-1), 8),
    ]))
    story.append(zones_table)
    story.append(Spacer(1, 20))

    # Section 2: Site Acquisition & Coordinates
    if land_research:
        story.append(Paragraph("5. Recommended Sites & Property Acquisition", h1_style))
        story.append(Paragraph(
            "This section maps where the business should be placed and compares leasing against acquiring land. "
            "Land-for-sale research is attempted through Bright Data SERP. If no live listing price is extracted, "
            "the financial figures are marked as unverified planning estimates and must be validated with a broker or land registry.",
            body_style
        ))

        diag_text = (
            f"Land listing source: <b>{_safe(land_diagnostics.get('source', 'unknown'))}</b>; "
            f"status: <b>{_safe(land_diagnostics.get('status', 'unknown'))}</b>; "
            f"live listings parsed: <b>{_safe(land_diagnostics.get('live_listing_count', 0))}</b>."
        )
        story.append(Paragraph(diag_text, body_style))
        story.append(Spacer(1, 8))

        site_headers = [
            Paragraph("Zone / Placement", table_header_style),
            Paragraph("Coordinates / Google Maps", table_header_style),
            Paragraph("Acquisition Decision", table_header_style),
        ]
        site_rows = [site_headers]
        for item in land_research:
            maps_text = (
                f"{item.get('lat')}, {item.get('lng')}<br/>"
                f"<a href='{_safe(item.get('google_maps_url'))}'>Open coordinate in Google Maps</a>"
                if item.get("google_maps_url")
                else "Coordinate unavailable"
            )
            site_rows.append([
                Paragraph(
                    f"<b>{_safe_md(item.get('zone_name'))}</b><br/>{_safe_md(item.get('site_note'))}",
                    table_body_style
                ),
                Paragraph(maps_text, table_body_style),
                Paragraph(
                    f"<b>{_safe_md(item.get('decision'))}</b><br/>Source: {_safe_md(item.get('source'))}",
                    table_body_style
                ),
            ])

        site_table = Table(site_rows, colWidths=[220, 145, 139])
        site_table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), c_secondary),
            ('ALIGN', (0,0), (-1,-1), 'LEFT'),
            ('VALIGN', (0,0), (-1,-1), 'TOP'),
            ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor("#CBD5E1")),
            ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.white, c_light]),
            ('TOPPADDING', (0,0), (-1,-1), 6),
            ('BOTTOMPADDING', (0,0), (-1,-1), 6),
            ('LEFTPADDING', (0,0), (-1,-1), 7),
            ('RIGHTPADDING', (0,0), (-1,-1), 7),
        ]))
        story.append(site_table)
        story.append(Spacer(1, 12))

        economics_headers = [
            Paragraph("Zone", table_header_style),
            Paragraph("Lease Model", table_header_style),
            Paragraph("Own / Land-Bank Model", table_header_style),
            Paragraph("Rent vs Buy", table_header_style),
        ]
        economics_rows = [economics_headers]
        for item in land_research:
            economics_rows.append([
                Paragraph(f"<b>{_safe_md(item.get('zone_name'))}</b><br/>{int(item.get('target_lot_sqm', 0))} sqm target lot", table_body_style),
                Paragraph(
                    f"{_money(item.get('estimated_rent_php_month'), market_profile)}/mo<br/>{_money(item.get('estimated_rent_php_year'), market_profile)}/yr",
                    table_body_style
                ),
                Paragraph(
                    f"{_money(item.get('estimated_land_purchase_php'), market_profile)} purchase est.<br/>"
                    f"{_money(item.get('estimated_land_php_per_sqm'), market_profile)}/sqm land basis<br/>"
                    f"{_money(item.get('ownership_carrying_cost_php_month'), market_profile)}/mo carrying cost",
                    table_body_style
                ),
                Paragraph(
                    f"{item.get('years_of_rent_to_purchase')} years of rent equals land price<br/>"
                    f"<b>{_safe_md(item.get('decision'))}</b>",
                    table_body_style
                ),
            ])

        economics_table = Table(economics_rows, colWidths=[100, 115, 165, 124])
        economics_table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), c_dark),
            ('ALIGN', (0,0), (-1,-1), 'LEFT'),
            ('VALIGN', (0,0), (-1,-1), 'TOP'),
            ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor("#CBD5E1")),
            ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.white, c_light]),
            ('TOPPADDING', (0,0), (-1,-1), 6),
            ('BOTTOMPADDING', (0,0), (-1,-1), 6),
            ('LEFTPADDING', (0,0), (-1,-1), 7),
            ('RIGHTPADDING', (0,0), (-1,-1), 7),
        ]))
        story.append(economics_table)
        story.append(Spacer(1, 12))

        listing_rows = [[
            Paragraph("Zone", table_header_style),
            Paragraph("Land Listing Search Evidence", table_header_style),
            Paragraph("Parsed Price", table_header_style),
        ]]
        for item in land_research:
            listings = item.get("listings") or []
            if not listings:
                listing_rows.append([
                    Paragraph(f"<b>{_safe_md(item.get('zone_name'))}</b>", table_body_style),
                    Paragraph(
                        f"No live listing price parsed. Search query used: {_safe_md(item.get('search_query'))}",
                        table_body_style
                    ),
                    Paragraph("Unverified estimate", table_body_style),
                ])
                continue

            for listing in listings[:2]:
                listing_rows.append([
                    Paragraph(f"<b>{_safe_md(item.get('zone_name'))}</b>", table_body_style),
                    Paragraph(
                        f"<b>{_safe_md(listing.get('title'))}</b><br/>{_safe_md(listing.get('snippet'))}",
                        table_body_style
                    ),
                    Paragraph(
                        _money(listing.get("parsed_price_php"), market_profile) if listing.get("parsed_price_php") else "Not parsed",
                        table_body_style
                    ),
                ])

        listing_table = Table(listing_rows, colWidths=[95, 314, 95])
        listing_table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), c_secondary),
            ('ALIGN', (0,0), (-1,-1), 'LEFT'),
            ('VALIGN', (0,0), (-1,-1), 'TOP'),
            ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor("#CBD5E1")),
            ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.white, c_light]),
            ('TOPPADDING', (0,0), (-1,-1), 6),
            ('BOTTOMPADDING', (0,0), (-1,-1), 6),
            ('LEFTPADDING', (0,0), (-1,-1), 7),
            ('RIGHTPADDING', (0,0), (-1,-1), 7),
        ]))
        story.append(listing_table)
        story.append(Spacer(1, 20))

    # Section 5: Opportunity Analysis
    recommendation = zones[0] if zones else {}
    story.append(Paragraph("6. Strategic Selection & Market Saturation", h1_style))
    story.append(Paragraph(
        f"Based on live evidence and agent consensus, the primary location choice is <b>{_safe_md(recommendation.get('name', 'No validated site'))}</b>. "
        f"This location yields an Opportunity Score of <b>{recommendation.get('opp_score', 0)}/10</b>. "
        f"The competitor count represents Bright Data search evidence, not a guaranteed registry of all operating competitors. "
        f"Traffic confidence is <b>{_safe_md(recommendation.get('traffic_confidence', 'unknown'))}</b> and competitor confidence is "
        f"<b>{_safe_md(recommendation.get('competitor_confidence', 'unknown'))}</b>. "
        f"Population evidence for {city} is <b>{_safe_md(population_label)}</b> "
        f"with <b>{_safe_md(demographics.get('confidence', 'unknown'))}</b> confidence. "
        f"Nearby demand-anchor evidence for this site: {_safe_md(_anchor_counts_text(anchor_lookup.get(recommendation.get('name')) or {}))}.",
        body_style
    ))
    
    comp_list = ", ".join(recommendation.get('competitors', []))
    story.append(Paragraph(f"<b>Key competitor evidence:</b> {_safe_md(comp_list or 'No live competitor evidence returned')}", body_style))
    story.append(Spacer(1, 15))

    # Section 6: Seasonal Demand Forecast
    story.append(Paragraph("7. Seasonal Demand Projections", h1_style))
    story.append(Paragraph(
        "The following quarterly demand figures are planning scenarios, not confirmed sales facts. "
        "They should be validated against live POS benchmarks, local foot-traffic counts, and event calendars before investment decisions:",
        body_style
    ))
    
    season_rows = [[Paragraph("<b>Quarter / Period</b>", table_header_style), Paragraph("<b>Demand Volume Index</b>", table_header_style), Paragraph("<b>Strategic Marketing Focus</b>", table_header_style)]]
    for q, val in seasonal_forecast.items():
        desc = ""
        if "Q1" in q:
            desc = "Baseline planning period. Validate commuter and repeat-customer behavior."
        elif "Q2" in q:
            desc = "Warm-season scenario. Validate local weather, tourism, and school/work calendars."
        elif "Q3" in q:
            desc = "Mid-year scenario. Validate local traffic dips or peaks before staffing commitments."
        elif "Q4" in q:
            desc = "Holiday scenario. Validate shopping, gifting, and event traffic with live evidence."
        
        season_rows.append([
            Paragraph(f"<b>{q}</b>", table_body_style),
            Paragraph(val, table_body_style),
            Paragraph(desc, table_body_style)
        ])
    
    season_table = Table(season_rows, colWidths=[100, 120, 284])
    season_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), c_dark),
        ('ALIGN', (0,0), (-1,-1), 'LEFT'),
        ('VALIGN', (0,0), (-1,-1), 'TOP'),
        ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor("#CBD5E1")),
        ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.white, c_light]),
        ('TOPPADDING', (0,0), (-1,-1), 6),
        ('BOTTOMPADDING', (0,0), (-1,-1), 6),
        ('LEFTPADDING', (0,0), (-1,-1), 8),
        ('RIGHTPADDING', (0,0), (-1,-1), 8),
    ]))
    story.append(season_table)
    story.append(Spacer(1, 20))

    # Section 4: Local Events & Festival Research
    if events:
        story.append(Paragraph("8. Local Events & Festival Research (Bright Data)", h1_style))
        story.append(Paragraph(
            f"Using Bright Data search engine proxy queries, our location scout compiled local events and calendar peaks "
            f"in {city}. These events drive local consumer traffic and shape strategic commercial activations:",
            body_style
        ))
        story.append(Spacer(1, 10))
        
        event_rows = [[Paragraph("<b>Event / Festival Name</b>", table_header_style), Paragraph("<b>Target Period</b>", table_header_style), Paragraph("<b>Commercial Retail Impact</b>", table_header_style)]]
        for e in events:
            event_rows.append([
                Paragraph(f"<b>{_safe_md(e['name'])}</b>", table_body_style),
                Paragraph(_safe_md(e['period']), table_body_style),
                Paragraph(_safe_md(e['impact']), table_body_style)
            ])
        
        event_table = Table(event_rows, colWidths=[130, 110, 264])
        event_table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), c_secondary),
            ('ALIGN', (0,0), (-1,-1), 'LEFT'),
            ('VALIGN', (0,0), (-1,-1), 'TOP'),
            ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor("#CBD5E1")),
            ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.white, c_light]),
            ('TOPPADDING', (0,0), (-1,-1), 6),
            ('BOTTOMPADDING', (0,0), (-1,-1), 6),
            ('LEFTPADDING', (0,0), (-1,-1), 8),
            ('RIGHTPADDING', (0,0), (-1,-1), 8),
        ]))
        story.append(event_table)
        story.append(Spacer(1, 20))

    # Page Break for the detailed plan content
    story.append(PageBreak())

    # Section 9: Detailed Business Strategy
    story.append(Paragraph("9. Detailed Business Strategy & Launch Roadmap", h1_style))
    story.append(Spacer(1, 10))

    full_plan = str(plan_details.get("full_plan") or "").strip()
    if full_plan:
        story.append(Paragraph("Agent-Written Comprehensive Plan", h2_style))
        _append_clean_blocks(story, full_plan, body_style, h2_style)
        story.append(Spacer(1, 12))

    sections_to_add = [
        ("Executive Summary", plan_details.get("executive_summary", "")),
        ("Target Customer Demographics", plan_details.get("demographics", "")),
        ("Unique Value Proposition (UVP)", plan_details.get("uvp", "")),
        ("Marketing & Launch Strategy", plan_details.get("marketing", "")),
        ("Financial Estimate (Year 1)", plan_details.get("financials", ""))
    ]

    for sec_title, sec_content in sections_to_add:
        if sec_content:
            story.append(Paragraph(sec_title, h2_style))
            # Split lines by newlines to preserve formatting
            for p_text in sec_content.split('\n\n'):
                if p_text.strip():
                    story.append(Paragraph(_safe_md(p_text.strip()).replace('\n', '<br/>'), body_style))
            story.append(Spacer(1, 10))

    # Build PDF
    doc.build(story, canvasmaker=NumberedCanvas)
    print(f"PDF successfully generated at: {file_path}")
